[tool.poetry]
name = "imoco"
version = "0.1.0"
description = "imoco reconstructions"
authors = ["Luis Torres <luigibytes@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9"
numpy = "^1.23.4"
requests = "^2.28.1"
matplotlib = "^3.6.1"
nibabel = "^4.0.2"
h5py = "^3.7.0"
sigpy = "^0.1.23"
scikit-image = "^0.19.3"
pandas = "^1.5.0"
torch = "^1.12.1"
simpleitk = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
