#!/usr/bin/env bash
export h5=$1/MRI_Raw.h5
export ksp=$1/ksp.npy
export coord=$1/coord.npy
export dcf=$1/dcf.npy
export kspL=$1/kspL.npy
export coordL=$1/coordL.npy
export dcfL=$1/dcfL.npy
export kspB=$1/kspB.npy
export coordB=$1/coordB.npy
export dcfB=$1/dcfB.npy
export mps=$1/mps.npy
export wrps=$1/wrps.npy
export img=$1/img.h5
export grd=$1/grd.npy

export resp=$1/resp.npy
export mrimg=$1/mrimg.npy
export sgw=$1/sgw.npy
export sgimg=$1/sgimg.h5
